using UnityEngine;using UnityEditor;using System.IO;using System.Collections.Generic;
[InitializeOnLoad]public static class WindowStormVerify{
static WindowStormVerify(){EditorApplication.delayCall+=()=>{if(File.Exists("Temp/window_storm_verify.request")&&!EditorApplication.isPlaying){Verify();File.Delete("Temp/window_storm_verify.request");}};}
static void Verify(){var s=Object.FindFirstObjectByType<StealthGame.WindowStorm>();foreach(var pane in s.rainWindows){var scale=pane.transform.localScale;scale.x=scale.x>1?1.30f:.96f;scale.y=1.40f;pane.transform.localScale=scale;UnityEditor.EditorUtility.SetDirty(pane.transform);}UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(s.gameObject.scene);UnityEditor.SceneManagement.EditorSceneManager.SaveScene(s.gameObject.scene);var old=s.viewer;var camObject=new GameObject("Storm verification camera");var c=camObject.AddComponent<Camera>();c.CopyFrom(old.GetComponent<Camera>());c.enabled=false;
var rendererStates=new Dictionary<Renderer,bool>();foreach(var r in GameObject.Find("Player").GetComponentsInChildren<Renderer>()){rendererStates[r]=r.enabled;r.enabled=false;}
var light=s.windowLights[0];float nearest=float.MaxValue;foreach(var l in s.windowLights){float distance=(l.transform.position-old.position).sqrMagnitude;if(distance<nearest){nearest=distance;light=l;}}
var inward=Vector3.ProjectOnPlane(light.transform.forward,Vector3.up).normalized;var right=Vector3.Cross(Vector3.up,inward);Vector3 center=light.transform.position;
try{s.viewer=c.transform;c.transform.position=center+inward*2+right*.5f;c.transform.LookAt(center-Vector3.up*.25f);s.ApplyVisuals(0);Capture(c,"Temp/window_rain_normal.png");c.transform.position=center+inward*.7f+right*.8f;c.transform.LookAt(center+inward*3-Vector3.up*1.4f);s.ApplyVisuals(1);int enabled=0;foreach(var l in s.windowLights)if(l.enabled)enabled++;Capture(c,"Temp/window_shadow_flash.png");s.ApplyVisuals(0);bool off=true;foreach(var l in s.windowLights)off&=!l.enabled;
File.WriteAllText("Temp/window_storm_verification.txt","nearbyFlashLights="+enabled+" maximum="+s.maximumNearbyLights+" lightsOffAfterFlash="+off+" audioReference="+(s.stormAudio!=null)+" audioLoop="+s.stormAudio.loop+" cueCount="+s.lightningTimes.Length+" shaderErrors="+ShaderUtil.ShaderHasError(Shader.Find("StealthGame/RainOutsideWindow")));}
finally{s.ApplyVisuals(0);s.viewer=old;foreach(var pair in rendererStates)pair.Key.enabled=pair.Value;Object.DestroyImmediate(camObject);}}
static void Capture(Camera c,string path){var rt=RenderTexture.GetTemporary(1280,720,24);var previous=RenderTexture.active;Texture2D tex=null;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex=new Texture2D(1280,720,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1280,720),0,0);tex.Apply();File.WriteAllBytes(path,tex.EncodeToPNG());}finally{c.targetTexture=null;RenderTexture.active=previous;RenderTexture.ReleaseTemporary(rt);if(tex!=null)Object.DestroyImmediate(tex);}}
}
